// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('Verifier');
// Test verification with correct proof
contract('Verifier',accounts =>{
    const account_one =accounts[0];
    describe('Test verification with correct proof',function(){
        beforeEach(async function(){
            this.contract= await Verifier.new({from: account_one});
        })

        it ('Test verification with correct proof', async function(){
            const {proof:{a,b,c},inputs:input}=proof;
            let result=await this.
        })
    })
})
// - use the contents from proof.json generated from zokrates steps

    
// Test verification with incorrect proof
